### ISSUE TITLE
Privacy Issue: Provides IGC files for unregistered devices

### ISSUE THREAD

**Issue by kerel-fs** [glidernet/ogn-gateway-web#1]
Currently there are IGC files for all devices received by OGN since 2016-07-02 in `/var/www/html/igc`,
including **unregistered devices**. See
http://ognstats.ddns.net:8088/~odroid/cgi-bin/igc-list-dirs.py

Please distribute IGC files only for registered devices.

Behavior of other clients:
- [KTrax Logbook](http://ktrax.kisstech.ch/logbook/) provides takeoff/landing time of registered devices
- [ogn-live](live.glidernet.org) provides the flight path of all devices at the current day
- [KTrax Liverange](http://ktrax.kisstech.ch/flarm-liverange/) provides the last known position of all devices in the last 28 days

**Comment by kerel-fs** [comment]
@wbuczak Please stop the distribution of logs for unregistered devices!

CC: @snip

**Comment by kerel-fs** [comment]
Thanks for fixing this issue.

**Comment by wbuczak** [comment]
Good point. Thanks for reminding me of that !  I will take care of it ASAP!

The gateway will be logging IGCs only for these aircraft which:
 - register in OGN database
 - allow tracking

**Comment by kerel-fs** [comment]
Oh, ok, my message wasn't sarcastic, I really thought this issue would've been fixed.
Were are these IGC-Files now? An IRC-user in #glidernet@freenode just asked for the functionality your services offers. :smile:

**Comment by wbuczak** [comment]
Currently the process I run (ogn-gateway-stats) is only accumulating
statistics. The IGC logging in my service has been switched off. I will
re-enable it once I fix the issue with logging what I'm not supposed to log.

There is, however another logging process (run by Seb) and it logs all the
tracks, but it is kept ONLY for the SAR requests or individual requests of
owners. Not available to public.

In contrary, I want my service to be available publicly, but of course only
for these who are registered and allow tracking.

Cheers
Wojtek

**Comment by wbuczak** [comment]
Fixed. But not in this module, but in the ogn-gatewa-java. 

The program will only log IGCs for these aircraft who are registered and have tracking flag on in the OGN db

https://github.com/glidernet/ogn-gateway-java/commit/6e1d3ea43c6621e02f5d8e3a1927974a4009b5f6

**Comment by kerel-fs** [comment]
Great, thanks for clarification and this fix!
